const COMMAND_INSERT_TEXT = 'COMMAND_INSERT_TEXT';
const COMMAND_INSERT_UNEDITABLE_NODE = 'COMMAND_INSERT_UNEDITABLE_NODE';
const COMMAND_INSERT_PARAGRAPH = 'COMMAND_INSERT_PARAGRAPH';
const COMMAND_REMOVE_NODE = 'COMMAND_REMOVE_NODE';
const COMMAND_INSERT_PARAGRAPH_AFTER = 'COMMAND_INSERT_PARAGRAPH_AFTER';
const COMMAND_UNDO = 'COMMAND_UNDO';

// internal commands
const COMMAND_REPLACE_TEXT = 'COMMAND_REPLACE_TEXT';
const COMMAND_REPLACE_PARAGRAPH = 'COMMAND_REPLACE_PARAGRAPH';

export {
  COMMAND_INSERT_TEXT,
  COMMAND_INSERT_UNEDITABLE_NODE,
  COMMAND_INSERT_PARAGRAPH,
  COMMAND_REMOVE_NODE,
  COMMAND_INSERT_PARAGRAPH_AFTER,
  COMMAND_UNDO,
  COMMAND_REPLACE_TEXT,
  COMMAND_REPLACE_PARAGRAPH,
};
