export const COMMAND_INSERT_TEXT = 'COMMAND_INSERT_TEXT';
export const COMMAND_UNDO = 'COMMAND_UNDO';
export const COMMAND_INSERT_EMOJI = 'COMMAND_INSERT_EMOJI';
export const COMMAND_INSERT_PARAGRAPH = 'COMMAND_INSERT_PARAGRAPH';

// internal commands
export const COMMAND_REPLACE_TEXT = 'COMMAND_REPLACE_TEXT';
export const COMMAND_REPLACE_PARAGRAPH = 'COMMAND_REPLACE_PARAGRAPH';
