# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build playground

on:
  push:
    branches:
      - master
    paths:
      - 'playground/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build playground
        run: |
          pnpm -C theodore build
          pnpm -C playground build

      - name: Build Docker image
        run: |
          cd playground
          docker build -t ghcr.io/fatemehkarimi/theodore-playground:${{ github.run_number }} .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Push Docker Image
        run: |
          docker push ghcr.io/fatemehkarimi/theodore-playground:${{ github.run_number }}
      # - name: Create and push git tag
      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
          
      #     TAG="$(git rev-parse --short=7 HEAD)-${{ github.run_number }}"
      #     git tag $TAG
          
      #     git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
